require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/service_contracts", type: :request do

  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "Should return service contract" do
      service_contract = FactoryBot.create(:service_contract)

      get v1_service_contracts_url, headers: valid_headers, as: :json
      expect(response).to have_http_status(200)
      expect(JSON.parse(response.body)).to eq([JSON.parse(service_contract.to_json(only: [:id, :company_name]))])
    end
  end

end
